import { chromium } from 'playwright';
const BASE = process.env.BASE || 'http://localhost:8766';
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
const erros=[]; p.on('pageerror', e => erros.push(e.message)); p.on('console', m => m.type()==='error' && !/ERR_TUNNEL|fonts/.test(m.text()) && erros.push(m.text()));
const ok = (c, m) => console.log(c ? 'OK  ' : 'FALHA', m);
await p.goto(BASE + '/'); await p.waitForTimeout(1800);
ok(await p.locator('#selecao svg').count() > 0, 'selecao da temporada desenhada no topo');
ok(await p.locator('#elenco .carta').count() > 5, 'cartas do elenco');
ok(await p.locator('#elenco .carta .carta-figura svg circle').count() === 0, 'carta so com a camisa (sem boneco)');
ok(await p.evaluate(() => getComputedStyle(document.querySelector('#elenco .carta-eixos div')).backgroundColor === 'rgba(0, 0, 0, 0)'), 'stats em barrinha (sem caixinha colorida)');
ok(await p.locator('.campinho .no-campo').count() > 5, 'campinho do time com jogadores clicaveis');
await p.locator('#elenco .carta').first().click(); await p.waitForTimeout(300);
ok(await p.evaluate(() => document.getElementById('ficha').open), 'ficha abre');
ok(await p.evaluate(() => getComputedStyle(document.getElementById('ficha')).backgroundColor.includes('0.72')), 'ficha em vidro');
await p.mouse.click(20, 450); await p.waitForTimeout(200);
ok(await p.evaluate(() => !document.getElementById('ficha').open), 'clicar fora fecha a ficha');
await p.click('#abrir-vitrine'); await p.waitForTimeout(300);
ok(/Palha 25%/.test(await p.locator('#chances').textContent()), 'chances aparecem');
for (let i=0;i<3;i++){ await p.click('#palco .envelope'); await p.waitForTimeout(350); } await p.waitForTimeout(900);
ok(await p.locator('#palco .carta').count() === 5, 'envelope abre 5 em 3 cliques');
await p.waitForTimeout(2600); await p.screenshot({ path: `testes/resultados/home-envelope.png` });
await p.click('#vitrine-fechar');
await p.goto(BASE + '/#jogador-' + (await p.evaluate(() => 0))); 
const dist = await p.evaluate(() => { const c={}; for (let i=0;i<4000;i++){ const j=sortear(estado.r); const n=nivel(j.overall).id; c[n]=(c[n]||0)+1;} return c; });
console.log('sorteio 4000:', JSON.stringify(dist));
ok(erros.length === 0, 'sem erro de JS ' + JSON.stringify(erros));
await p.evaluate(() => scrollTo(0,0)); await p.screenshot({ path: `testes/resultados/home-topo.png` });
await b.close();
